<?php

namespace AppBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
	const SUBMITIONS_LIMIT = 3;

	public function getNumberOfSubmittions($ip) {
		$query = $this->createQueryBuilder('nw')
			->select('COUNT(nw.id)')
			->where("nw.ip = :ip")
		    ->setParameter('ip', $ip);
		$result = $query->getQuery()->getSingleScalarResult();
		return $result;
	}
}
