<?php

namespace AppBundle\Repository;

/**
 * ProductFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
