<?php

namespace AppBundle\Repository;

/**
 * StatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusesRepository extends \Doctrine\ORM\EntityRepository
{
}
