<?php

namespace AppBundle\Repository;

/**
 * SubCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
